#
# Copyright (C) Philip Helger
#
# All rights reserved.
#

# Should be set to "false" in production
global.debug=false
# Should be set to "true" in production
global.production=false

# Should be set to the absolute path to store some data in production
webapp.datapath=conf/
webapp.checkfileaccess=false
# Should be set to "false" in production
webapp.testversion=true
