#
# Copyright (C) Philip Helger
#
# All rights reserved.
#

# Should be set to "false" in production
global.debug=false
# Should be set to "true" in production
global.production=true

# Should be set to the absolute path to store some data in production
webapp.datapath=/phorm/data
webapp.checkfileaccess=false
# Should be set to "false" in production
webapp.testversion=true

# This is the secret token you need to pass in all API calls to get a response
# Please customize to your needs before deploying
# [CHANGEME]
# See also "application.properties"
phorm.api.requiredtoken=phorm-dev-token
