#
# Copyright (C) 2022-2024 Philip Helger
#
# All rights reserved.
#

# Should be set to "false" in production
global.debug=false
# Should be set to "true" in production
global.production=false

# Should be set to the absolute path to store some data in production
webapp.datapath=conf/
webapp.checkfileaccess=false
# Should be set to "false" in production
webapp.testversion=true

# This is the secret token you need to pass in all API calls to get a response
# Please customize to your needs before deploying
# [CHANGEME]
# See also "application.docker.properties"
valsvc.api.requiredtoken=4cKyX6OKBs80nWPyOamn
