#
# Copyright (C) Philip Helger
#
# All rights reserved.
#

# Application version number - this is generated automatically
version=${project.version}
# Build timestamp
timestamp=${maven.build.timestamp}
